spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: foobared
      database: 0
      timeout: 10000
      lettuce: 
        pool:
          max-active: 8  # 连接池最大连接数
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 8    # 连接池中的最大空闲连接
          min-idle: 0    # 连接池中的最小空闲连接
          time-between-eviction-runs: 1000 # 空闲对象逐出器线程的运行间隔时间